name: api
description: A new Flutter project.

version: 1.0.0+1
environment:
    sdk: '>=2.1.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.2
    google_fonts: ^1.1.0
    rflutter_alert: ^1.1.0
    progress_dialog: ^1.2.4
    http: ^0.12.2
    convex_bottom_bar: ^2.4.1
    shared_preferences: ^0.5.12
    convert: ^2.1.1
    flutter_svg: ^0.19.0
    hexcolor: ^1.0.4
    dio: ^3.0.10
    flutter_spinkit: ^4.1.2+1
    foldable_sidebar: ^1.0.0
    awesome_dialog: ^1.2.0
    flutter_secure_storage: ^3.3.4
    form_field_validator: ^1.0.1
    timer_builder: ^1.3.0
    flutter_splash_screen: ^0.1.0
    animated_splash: ^1.0.0
    your_splash: ^0.2.1
    device_apps: ^1.2.0
    flutter_appavailability: ^0.0.21
    animated_splash_screen: ^1.0.1
    custom_splash: ^0.0.2
    circle_bottom_navigation: ^1.0.6
    awesome_button: ^1.0.2
    giffy_dialog: ^1.8.0
    easy_dialog: ^1.0.5
    smart_progress_bar: ^0.1.6
    flutter_easyloading: ^2.0.0
    customprompt: ^0.2.6+9
    flutter_progress_dialog: ^0.1.0
    ndialog: ^3.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: '^0.7.3'
    change_app_package_name: ^0.1.2

flutter_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/images/logo.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/icons/
        - assets/google_fonts/
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: MeriendaOne
          fonts:
              - asset: assets/google_fonts/MeriendaOne-Regular.ttf
                weight: 600
        - family: Sriracha
          fonts:
              - asset: assets/google_fonts/Sriracha-Regular.ttf
                weight: 700
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
